Feature/dataservices mongo
Grupo-G03-4SOAT-FIAP/rms-api-pagamentos pull request #8
Opened 2024-05-05 21:12 UTC by DiegoOLiveira-dev

Criacao do mongo data services, implementação do repository de gravacao de pagamentos e retorno do mercado pago no mongo DB e inclusao do mongo db e mongo express no docker compose para testes locais.

2024-05-05 21:15 UTC, anaplopes approved these changes

2024-05-05 21:50 UTC, dannevesdantas requested changes
Alguns ajustes precisam ser feitos para passar pelo Sonar.

2024-05-05 21:50 UTC, dannevesdantas commented on src/domain/pagamento/entities/retorno_mp.entity.ts
Acredito que a classe `RetornoMP` não se enquadra como Entidade nesse contexto. Acredito que a classe `RetornoMP` se enquadraria melhor como um `DTO`.

2024-05-06 23:26 UTC, dannevesdantas approved these changes

2024-05-06 23:27 UTC, merged